### ISSUE TITLE
better file organization proposal

### ISSUE THREAD

**Issue by pashute** [barrymichaeldoyle/capo-keys#1]
After contemplating, I want to propose a better file organization:

Each screen and component has its own `folder`. The folder contains the main .js file (named as `<screennameOrComponentname>.js` and not called index.js) and a file for `styles`, `events` (e.g. actions), and `handers` (e.g. reducers)

If a screen has components used only in that screen, another components folder should be opened under the screen named `<screenname>Components`

    components\ // for shared components 
    screens\         // for all screens:  mainScreen, chordsScreen (the modal screen) 
    appState\      // for redux related files    
 
    // mainscreen
    screens\mainScreen\
    screens\mainScreen\mainScreen.js // the main file
    screens\mainScreen\mainScreenStyles.js
    screens\mainScreen\mainScreenHandlers.js // the reducers
    screens\mainScreen\mainScreenEvents.js // the actions
    // mainscreen components
    screens\mainScreen\components

    screens\mainScreen\components\chordSection\chordSection.js
    screens\mainScreen\components\chordSection\chordSectionStyles.js
    screens\mainScreen\components\chordSection\chordSectionEvents.js
    screens\mainScreen\components\chordSection\chordSectionHandlers

    screens\mainScreen\components\capoSection\capoSection.js
    screens\mainScreen\components\capoSection\capoSectionStyles.js
    screens\mainScreen\components\capoSection\capoSectionEvents.js
    screens\mainScreen\components\capoSection\capoSectionHandlers

**Comment by barrymichaeldoyle** [comment]
This repo is based off a YouTube tutorial I made on [my channel](https://www.youtube.com/BarryMichaelDoyle). I can't make updates to these files because the videos the file are related to have already been recorded. That would confuse new students who come to the channel.

**Comment by pashute** [comment]
Yes, I know. I'm suggesting this for future development you make.
